### ISSUE TITLE
Setup basic authentication using passport.js

### ISSUE THREAD

**Issue by cyber-venom003** [Elevate-Lab/seroton-inn-backend#14]
# Feature Request

### Describe your problem

Setup the authentication methods using Google and Email. 

### Describe the solution you'd like

Setup passport.js in the project. Refer [PassportJS Docs](http://www.passportjs.org/docs/) and setup according to our needs.

**Comment by 2802harsh** [comment]
I want to work on this

**Comment by uglyprincess** [comment]
Sure, @2802harsh ! 🥳

**Comment by 2802harsh** [comment]
@Tlazypanda @cyber-venom003 pls review

**Comment by cyber-venom003** [comment]
Nice work @2802harsh
