### ISSUE TITLE
Create Comment Schema and its Endpoints

### ISSUE THREAD

**Issue by uglyprincess** [Elevate-Lab/seroton-inn-backend#33]
# Feature Request

### Describe your problem

Create a model for the comments that users can leave on any post. 

### Describe the solution you'd like

Naturally, each comment needs to be linked to the parent post on which it has been posted. Keep this in mind while designing the schema.

### Additional context

Also ensure that these comments have API endpoints (that is, the basic CRUD functionality).

**Comment by stygian-96** [comment]
@uglyprincess I want to work on this issue

**Comment by uglyprincess** [comment]
> @uglyprincess I want to work on this issue

Sure, go ahead!
