### ISSUE TITLE
creating posts route to read image of the post 

### ISSUE THREAD

**Issue by rush-tea** [Elevate-Lab/seroton-inn-backend#38]
# Feature Request

### Describe your problem

Till now there are two routes to view the postData, one for getting array of posts and second is for getting details of single post, from these two we cannot display images in frontend there is need to add another route to display the image of the post.

**Comment by rush-tea** [comment]
@stygian-96 can i work on this?

**Comment by stygian-96** [comment]
Yes! Go ahead! 🙌
