### ISSUE TITLE
Implementing feature for Profile pic upload 

### ISSUE THREAD

**Issue by rush-tea** [Elevate-Lab/seroton-inn-backend#40]
# Feature Request

### Describe your problem

Recently there is no any route to upload profile pic, also in profile model profile pic is declared as string, so there is need to change it to object to store the image data and also creates routes to upload and retrieve data.

**Comment by rush-tea** [comment]
@stygian-96 can i do this ?

**Comment by stygian-96** [comment]
Yes sure!!
