### ISSUE TITLE
Modifying userprofile routes

### ISSUE THREAD

**Issue by rush-tea** [Elevate-Lab/seroton-inn-backend#43]
# Feature Request

### Describe your problem

Currently in user profile routes we are searching users by google Id but in signup process we have two methods one is by google-oauth and other in normal way by creating new user in DB, so a user who has signup by normal process will not have googleId and user profile routes will not work. 

### Describe the solution you'd like

Since each user object in DB must be having normal user id so change the user profile routes to use the normal user id for different functions.

**Comment by rush-tea** [comment]
@stygian-96 I would like to work on this!!

**Comment by stygian-96** [comment]
Yes Sure!!
